### PR TITLE
travis: upload binary to s3 bucket

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
@eysteins was trying to get this working locally.

I think its a good idea to just deploy this to s3 whenever tests are passing.

@pasinskim what do you think?

### CODE REVIEW

**Comment by pasinskim** [comment]
Maybe, yes. Makes sense as we shouldn't require users to compile this themselves. Probably we should also add some docs on how to download and use it.

**Comment by GregorioDiStefano** [comment]
Yes, precisely. @eysteins is writing docs on how to compile this, but we can just provide a build from the build machine instead.

**Comment by pasinskim** [comment]
@GregorioDiStefano but we will need to change the configuration to actually build the binary. Previously it was supposed to be a library so we are not providing an actual `artifacts` binary AFAIK.

**Comment by GregorioDiStefano** [comment]
updated so artifacts tool is compiled.

**Pull request merged**
